import 'dart:ui';
import 'package:get/get.dart';

class LocalizationService extends Translations {
  static final List<String> langs = ['English', 'Hindi', 'Marathi'];
  static final List<Locale> locales = [
    Locale('en', 'US'),
    Locale('hi', 'IN'),
    Locale('mr', 'IN'),
  ];
  // Language codes to be used as short names
  static final List<String> langCodes = ['en', 'hi', 'mr'];

  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'search': 'Search',
          'advanced_search': 'Advanced Search',
          'list': 'List',
          'survey': 'Survey',
          'data': 'Data',
          'setting': 'Setting',
          'details': 'Details',
          'family': 'Family',
          'survey': 'Survey',
          'part no': 'Part no',
          'srn': 'Srn',
          'age': 'Age',
          'gender': 'Gender',
          'village': 'Village',
          'voter Id': 'Voter Id',
          'house No': 'House No',
          'address': 'Address',
          'booth': 'Booth',
          'Mobile-1': 'Mobile-1:-',
          'Mobile-2': 'Mobile-2:-',
          'Colour Code': 'Colour Code:-',
          'Caste': 'Caste:-',
          'Position': 'Position:-',
          'New address': 'New address:-',
          'Flate No': 'Flate No:-',
          'EmailID': 'Email ID:-',
          'DOB': 'DOB:-',
          'Demands': 'Demands:-',
          'Extra Info1': 'Extra Info1:-',
          'Extra Info2': 'Extra Info2:-',
          'Extra Info3': 'Extra Info3:-',
          'Extra Info4': 'Extra Info4:-',
          'Extra Info5': 'Extra Info5:-',
          'Extra Ckeck1': 'Extra Ckeck 1:-',
          'Extra Ckeck2': 'Extra Ckeck 2:-',
          'Voted': 'Voted:-',
          'Dead': 'Dead:-',
          'Surname': 'Surname',
          'First Name': 'First Name',
          'Middle Name': 'Middle Name',
          'From Age': 'From Age',
          'To Age': 'To Age',
          'Mobile No': 'Mobile No',
          'Part No': 'Part No',
          'Voter Id': 'Voter Id',
          'House No': 'House No',
          'Type your text here': 'Type your text here',
          'alphabetical list': 'Alphabetical list',
          'By Village': 'By Village ',
          'By Part No': 'By Part No',
          'By voiting center': 'By voiting center',
          'By Personnel': 'By Personnel',
          'By Surname': 'By Surname',
          'By Colour Code': 'By Colour Code',
          'Mobile No List': 'Mobile Number List',
          'VotercWithout Mobile': 'Voter Without Mobile List',
          'By Adderss': 'By Adderss',
          'By New Adderss': 'By New Adderss',
          'By Society': 'By Society',
          'By Gender': 'By Gender',
          'By Age': 'By Age',
          'By Caste': 'By Caste',
          'By Position': 'By Position',
          'By Dead': 'By Dead',
          'Repeated': 'Repeated',
          'Star Voter': 'Star Voter',
          'Extra Ckeck 1': 'Extra Ckeck 1',
          'Extra Ckeck 2': 'Extra Ckeck 2',
          'Extra Info 1': 'Extra Info1',
          'Extra Info 2': 'Extra Info2',
          'Extra Info 3': 'Extra Info3',
          'Extra Info 4': 'Extra Info4',
          'Extra Info 5': 'Extra Info5',
          'By House No': 'By House No',
          'Demands List': 'Demands List',
          'voted': 'Voted',
          'By Survey Team': 'By Survey Team',
          'By Taluka': 'By Taluka',
          'Today BirthDay': 'Today BirthDay',
          'Slip Printer Report': 'Slip Printer Report',
          'Bluetooth Slip Report By User': 'Bluetooth Slip Report By User',
          'Assembly': 'Assembly',
          'Booth no': 'Booth no',
          'Srn': 'Srn',
          'Final Srno': 'Final Srno',
          'Name': 'Name',
          'Gat': 'Gat',
          'Export Cart': 'Export Cart',
          'Gan': 'Gan',
          'Assembly No': 'Assembly No',
          'mobile-1': 'Mobile-1',
          'mobile-2': 'Mobile-2',
          'Dob': 'Dob',
          'demands': 'Demands',
          'Personnel': 'Personnel',
          'Cast': 'Cast',
          'position': 'Position',
          'New Address': 'New Address',
          'Society': 'Society',
          'Flat No': 'Flat No',
          'Booth': 'Booth',
          'Booth(English)': 'Booth(English)',
          'dead': 'Dead',
          'Total': 'Total',
          'Permission Denied': 'Permission Denied',
          'Rajyog Demo': 'Rajyog Demo',
          'You do not have permission to download the PDF. Please contact the administrator.':
              'You do not have permission to download the PDF. Please contact the administrator.',
          'Shirur - Assembly - Maharashtra Assembly Election':
              'Shirur - Assembly - Maharashtra Assembly Election',
          'Ok':'Ok',
          'description':'description',
          'assembly_name':'assembly_name',
          'name':'name',
        },
        'hi_IN': {
          'search': 'खोजें',
          'advanced_search': 'उन्नत खोज',
          'list': 'सूची',
          'survey': 'सर्वेक्षण',
          'data': 'डेटा',
          'setting': 'समायोजन',
          'details': 'विवरण',
          'family': 'परिवार',
          'survey': 'सर्वे',
          'part no': 'भाग संख्या',
          'srn': 'अनु. क्र.',
          'age': 'आयु',
          'gender': 'लिंग',
          'village': 'गाँव',
          'voter Id': 'मतदाता पहचान पत्र',
          'house No': 'मकान नंबर',
          'address': 'पता',
          'booth': 'बूथ',
          'Mobile-1': 'मोबाइल-1:-',
          'Mobile-2': 'मोबाइल-2:-',
          'Colour Code': 'रंग कोड:-',
          'Caste': 'जाति:-',
          'Position': 'पद:-',
          'New address': 'नया पता:-',
          'Flate No': 'फ्लैट नं.:-',
          'EmailID': 'ईमेल आईडी:-',
          'DOB': 'जन्म तिथि:-',
          'Demands': 'मांगों:-',
          'Extra Info1': 'अतिरिक्त जानकारी1:-',
          'Extra Info2': 'अतिरिक्त जानकारी2:-',
          'Extra Info3': 'अतिरिक्त जानकारी3:-',
          'Extra Info4': 'अतिरिक्त जानकारी4:-',
          'Extra Info5': 'अतिरिक्त जानकारी5:-',
          'Extra Ckeck1': 'अतिरिक्त जांच 1:-',
          'Extra Ckeck2': 'अतिरिक्त जांच 2:-',
          'Voted': 'मतदान किया गया:-',
          'Dead': 'मृत:-',
          'Surname': 'उपनाम',
          'First Name': 'पहला नाम',
          'Middle Name': 'मध्य नाम',
          'From Age': 'उम्र से',
          'To Age': 'उम्र तक',
          'Mobile No': 'मोबाईल नंबर',
          'Part No': 'भाग संख्या',
          'Voter Id': 'मतदाता पहचान पत्र',
          'House No': 'मकान नंबर',
          'Type your text here': 'यहां अपना पाठ लिखें',
          'alphabetical list': 'वर्णमाला सूची',
          'By Village': 'गांव के अनुसार',
          'By Part No': 'भाग संख्या द्वारा',
          'By voiting center': 'वोटिंग सेंटर द्वारा',
          'By Personnel': 'कार्मिक द्वारा',
          'By Surname': 'उपनाम से',
          'By Colour Code': 'रंग कोड के अनुसार',
          'Mobile No List': 'मोबाईल नंबर लिस्ट',
          'VotercWithout Mobile': 'मोबाइल के बिना मतदाता',
          'By Adderss': 'पते के अनुसार',
          'By New Adderss': 'नये पते से',
          'By Society': 'समाज द्वारा',
          'By Gender': 'लिंग के अनुसार',
          'By Age': 'वयानुसार',
          'By Caste': 'जाति के अनुसार',
          'By Position': 'पद के अनुसार',
          'By Dead': 'मृत द्वारा',
          'Repeated': 'दोहराया गया',
          'Star Voter': 'स्टार वोटर',
          'Extra Ckeck 1': 'अतिरिक्त जांच 1',
          'Extra Ckeck 2': 'अतिरिक्त जांच 2',
          'Extra Info 1': 'अतिरिक्त जानकारी1',
          'Extra Info 2': 'अतिरिक्त जानकारी2',
          'Extra Info 3': 'अतिरिक्त जानकारी3',
          'Extra Info 4': 'अतिरिक्त जानकारी4',
          'Extra Info 5': 'अतिरिक्त जानकारी5',
          'By House No': 'मकान नं.',
          'Demands List': 'मांग सूची',
          'voted': 'मतदान किया गया',
          'By Survey Team': 'सर्वेक्षण टीम द्वारा',
          'By Taluka': 'तालुका द्वारा',
          'Today BirthDay': 'आज जन्मदिन',
          'Slip Printer Report': 'स्लिप प्रिंटर रिपोर्ट',
          'Bluetooth Slip Report By User':
              'उपयोगकर्ता द्वारा ब्लूटूथ स्लिप रिपोर्ट',
          'Assembly': 'विधानसभा',
          'Booth no': 'बूथ संख्या',
          'Srn': 'अ क्र',
          'Final Srno': 'अंतिम अ .क्र',
          'Name': 'नाम',
          'Gat': 'गट',
          'Export Cart': 'कार्ट निर्यात करें',
          'Gan': 'गण',
          'Assembly No': 'विधानसभा संख्या',
          'mobile-1': 'मोबाइल-1',
          'mobile-2': 'मोबाइल-2',
          'Dob': 'जन्म तिथि',
          'demands': 'मांग',
          'Personnel': 'कार्मिक',
          'Cast': 'जाति',
          'position': 'स्थिती',
          'New Address': 'नया पता',
          'Society': 'समाज',
          'Flat No': 'फ्लॅट क्र',
          'Booth': 'बुथ',
          'Booth(English)': 'बूथ(अंग्रेजी)',
          'dead': 'मृत',
          'Total': 'कुल',
          'Rajyog Demo': 'राजयोग डेमो',
          'Shirur - Assembly - Maharashtra Assembly Election':
              'शिरूर - विधानसभा - महाराष्ट्र विधानसभा चुनाव',
          'Permission Denied': 'अनुमति नहीं मिली',
          'You do not have permission to download the PDF. Please contact the administrator.':
              'आपको पीडीएफ डाउनलोड करने की अनुमति नहीं है। कृपया व्यवस्थापक से संपर्क करें।',
          'Ok':'ठीक है',
           'description':'विवरण',
          'assembly_name':'असेंबली_नाम',
          'name':'नाम',
        },
        'mr_IN': {
          'search': 'शोधा',
          'advanced_search': 'प्रगत शोध',
          'list': 'यादी',
          'survey': 'सर्वेक्षण',
          'data': 'डेटा',
          'setting': 'सेटिंग',
          'details': 'महिती',
          'family': 'कुटुंब',
          'survey': 'सर्वेक्षण',
          'part no': 'भाग क्र',
          'srn': 'अनु. क्र.',
          'age': 'वय',
          'gender': 'लिंग',
          'village': 'गाव',
          'voter Id': 'मतदार आयडी',
          'house No': 'घर क्र',
          'address': 'पत्ता',
          'booth': 'बूथ',
          'Mobile-1': 'मोबाईल-०१:-',
          'Mobile-2': 'मोबाईल-2:-',
          'Colour Code': 'रंग कोड:-',
          'Caste': 'जात:-',
          'Position': 'स्थिती:-',
          'New address': 'नवीन पत्ता:-',
          'Flate No': 'फ्लॅट क्र:-',
          'EmailID': 'ईमेल आयडी:-',
          'DOB': 'जन्मतारीख:-',
          'Demands': 'मागण्या:-',
          'Extra Info1': 'अतिरिक्त माहिती1:-',
          'Extra Info2': 'अतिरिक्त माहिती2:-',
          'Extra Info3': 'अतिरिक्त माहिती3:-',
          'Extra Info4': 'अतिरिक्त माहिती4:-',
          'Extra Info5': 'अतिरिक्त माहिती5:-',
          'Extra Ckeck1': 'अतिरिक्त तपासणी 1:-',
          'Extra Ckeck2': 'अतिरिक्त तपासणी 2:-',
          'Voted': 'मतदान केले:-',
          'Dead': 'मृत:-',
          'Surname': 'आडनाव',
          'First Name': 'प्रथम नाव',
          'Middle Name': 'मधले नाव',
          'From Age': 'वयापासून',
          'To Age': 'वयापर्यंत',
          'Mobile No': 'मोबाईल नंबर',
          'Part No': 'भाग क्र',
          'Voter Id': 'मतदार आयडी',
          'House No': 'घर क्र',
          'Type your text here': 'तुमचा मजकूर येथे टाइप करा',
          'alphabetical list': 'वर्णक्रमानुसार यादी',
          'By Village': 'गावाने',
          'By Part No': 'भाग क्र',
          'By voiting center': 'मतदान केंद्राद्वारे',
          'By Personnel': 'कार्मिक द्वारे',
          'By Surname': 'आडनावाने',
          'By Colour Code': 'कलर कोडद्वारे',
          'Mobile No List': 'मोबाईल नंबर लिस्ट',
          'VotercWithout Mobile': 'मोबाईलशिवाय मतदार',
          'By Adderss': 'पत्त्यानुसार',
          'By New Adderss': 'नवीन पत्त्याद्वारे',
          'By Society': 'समाज द्वारा',
          'By Gender': 'लिंगानुसार',
          'By Age': 'वयानुसार',
          'By Caste': 'जातीने',
          'By Position': 'स्थितीनुसार',
          'By Dead': 'मृत करून',
          'Repeated': 'वारंवार',
          'Star Voter': 'स्टार मतदार',
          'Extra Ckeck 1': 'अतिरिक्त तपासणी 1',
          'Extra Ckeck 2': 'अतिरिक्त तपासणी 2',
          'Extra Info 1': 'अतिरिक्त माहिती1',
          'Extra Info 2': 'अतिरिक्त माहिती2',
          'Extra Info 3': 'अतिरिक्त माहिती3',
          'Extra Info 4': 'अतिरिक्त माहिती4',
          'Extra Info 5': 'अतिरिक्त माहिती5',
          'By House No': 'घर नं',
          'Demands List': 'मागणी यादी',
          'voted': 'मतदान केले',
          'By Survey Team': 'सर्वेक्षण पथकाद्वारे',
          'By Taluka': 'तालुक्याद्वारे',
          'Today BirthDay': 'आज वाढदिवस',
          'Slip Printer Report': 'स्लिप प्रिंटर अहवाल',
          'Bluetooth Slip Report By User':
              'वापरकर्त्याद्वारे ब्लूटूथ स्लिप अहवाल',
          'Assembly': 'विधानसभा',
          'Booth no': 'बुथ क्र',
          'Srn': 'अ क्र',
          'Final Srno': 'अंतिम अ .क्र ',
          'Name': 'नाव',
          'Gat': 'गट',
          'Export Cart': 'निर्यात कार्ट',
          'Gan': 'गं',
          'Assembly No': 'विधानसभा क्र',
          'mobile-1': 'मोबाईल-०१',
          'mobile-2': 'मोबाईल-०2',
          'Dob': 'जन्मतारीख',
          'demands': 'मागणी',
          'Personnel': 'कार्मिक',
          'Cast': 'जात',
          'position': 'स्थिती',
          'New Address': 'नवीन पत्ता',
          'Society': 'समाज',
          'Flat No': 'फ्लॅट क्र',
          'Booth': 'बुथ',
          'Booth(English)': 'बूथ (इंग्रजी)',
          'dead': 'मृत',
          'Total': 'एकूण',
          'Rajyog Demo': 'राजयोग डेमो',
          'Shirur - Assembly - Maharashtra Assembly Election':
              'शिरूर - विधानसभा - महाराष्ट्र विधानसभा निवडणूक',
          'Permission Denied': 'परवानगी नाकारली',
          'You do not have permission to download the PDF. Please contact the administrator.':
              'तुम्हाला PDF डाउनलोड करण्याची परवानगी नाही. कृपया प्रशासकाशी संपर्क साधा.',
          'Ok':'ठीक आहे',
          'description':'वर्णन',
          'assembly_name':'असेंब्लीचे नाव',
          'name':'नाव',
        },
      };

  void changeLocale(String lang) {
    final index =
        langs.indexOf(lang); // Find the index of the selected language
    if (index != -1) {
      final locale = locales[index];
      print('Selected locale: $locale');
      Get.updateLocale(locale); // Update the app locale
      final shortLangCode = langCodes[index];
      print('Selected language short code: $shortLangCode');
    } else {
      print('Language not found: $lang');
    }
  }
  String get currentShortLanguage {
    final currentLocale = Get.locale;
    if (currentLocale == null) return 'en'; // Default to English
    final index = locales.indexWhere((locale) =>
        locale.languageCode == currentLocale.languageCode &&
        locale.countryCode == currentLocale.countryCode);
        return index != -1 ? langCodes[index] : 'en';
  }

  Locale? _getLocaleFromLanguage(String lang) {
    for (int i = 0; i < langs.length; i++) {
      if (lang == langs[i]) return locales[i];
    }
    return Get.locale;
  }
}
